#!/bin/sh
# Variables
ADMIN_USER="${ADMIN_USER-$USER}"
export PAGER="less"

## Select an editor and set $EDITOR
for editor in nvim vim nanovi emacs
do
    if type "$editor" >/dev/null 2>&1
    then
        EDITOR="$editor"
        break
    fi
done
export EDITOR

export PATH="$HOME/.local/bin:/usr/lib/ccache/bin:$PATH"

# Aliases
## General aliases
### listing
#### List commands overriding ohmyz
#### status: 0: GNU ls; 1: BSD ls
if ls --help > /dev/null 2>&1
then
    # GNU ls
    alias ls='ls --color'
    alias la='ls -A'
    alias ll='ls -lh'
    alias l='ls -lAh'
else
    # BSD ls
    alias ls="ls -G"
    alias la="ls -GA"
    alias ll="ls -Glh"
    alias l="ls -GlAh"
fi

### other coreutils
alias du='du -Ph'
alias df='df -h'
#### do something as the admin
alias suy='sudo "-EHu${ADMIN_USER}"'
#### shredded revoval
alias srm="shred -fuvxzn100"
#### clear with clear delimeter
clear()
{
    for i in {0..10000}
    do
        printf 1
    done
    echo
    for i in {0..10000}
    do
        printf ' '
    done
    echo
    command clear
}
#### find files in $1 larger than $2
findlarger()
{
    sudo find "$1" -xdev -type f -size "+$2"
}
#### find files in $1 that are largest $2
findlargest()
{
    sudo du -ahx "$1" 2>/dev/null | sort -rh | head "-$2"
}
#### recursive download
alias rwget="command wget -cbrxp -np -U 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15'"
#### search command history
alias ghis='history|grep'
#### cp with progress
if type rsync >/dev/null 2>&1
then
    alias pcp="rsync -arP"
else
    alias pcp="cp -r"
fi
#### aria2c for wget
if type aria2c >/dev/null 2>&1
then
    alias wget="aria2c -x16"
fi

## Python
alias python='python3'
alias pip='pip3'
alias ipy='ipython'

## Homebrew
alias brew='sudo "-EHu${ADMIN_USER}" brew'
### install
alias binst='sudo "-EHu${ADMIN_USER}" brew install'
### uninstall
alias bunins='sudo "-EHu${ADMIN_USER}" brew uninstall'

## Git plugin
alias g="git"

## DNS
alias resolve="dns-sd -G v4v6"

## macOS
### remove the "unsafe" notice of an app
alias enableapp="sudo xattr -d com.apple.quarantine"

## Load other system-local aliases
[ -f ~/.local_aliases ] && . ~/.local_aliases

if ! [ "$ZSH_VERSION" = "" ]
then
    # Session history
    alias lochist="fc -lLI 1"
    # Reset terminal options
    precmd() { tput sgr0; printf "\x0f"; }
    # Zsh -s aliases
    if type unar >/dev/null 2>&1
    then
        alias -s gz="unar"
        alias -s tgz="unar"
        alias -s tar="unar"
        alias -s xz="unar"
        alias -s bz2="unar"
        alias -s Z="unar"
        alias -s zip="unar"
    else
        alias -s gz="gunzip"
        alias -s tgz="tar -zxvf"
        alias -s tar="tar -xvf"
        alias -s xz="unxz"
        alias -s bz2="bunzip2"
        alias -s Z="uncompress"
        alias -s zip="unzip"
    fi
else
    # Not zsh
    if [ "$PS1" ]
    then
        # Save history and reset terminal options
        PROMPT_COMMAND='history -a; tput sgr0; printf "\x0f"'
        # Use bash-completion, if available
        if [ -f /usr/share/bash-completion/bash_completion ]
        then
                . /usr/share/bash-completion/bash_completion
            # Prompt
            PS1='\[\033[01;34m\]\W\[\033[00m\]$(__git_ps1 " (%s)") $ '
        else
            PS1='\[\033[01;34m\]\W\[\033[00m\] $ '
        fi
    fi
fi

